apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - certificate.yaml
  - hpa.yaml

images:
  - name: 21520623/ministatus-backend
    newTag: 2dcb02d8f46fe221dec2dec4f931fecbc7cdfdbb
  - name: 21520623/ministatus-frontend
    newTag: 2dcb02d8f46fe221dec2dec4f931fecbc7cdfdbb
