apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - certificate.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: 21520623/ministatus-backend
    newTag: 0ee613d6726f0a86fc4595c117b3ae4107961f35
  - name: 21520623/ministatus-frontend
    newTag: 0ee613d6726f0a86fc4595c117b3ae4107961f35
