apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ministatus-backend
  namespace: ministatus
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ministatus-backend
  namespaceSelector:
    matchNames:
      - ministatus
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
