name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  backend:
    name: Backend CI
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    name: Frontend CI
    uses: ./.github/workflows/frontend-ci.yml

  docker-release:
    name: Docker Release
    needs:
      - backend
      - frontend

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write

    uses: ./.github/workflows/docker-release.yml

    secrets: inherit